apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-de-con-backend
spec:
  selector:
    matchLabels:
      app: app-de-con-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-de-con-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/c-leri/epsi-i2-k8s-project-backend:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: app-de-con-db
            - name: DB_NAME
              value: app_de_con
            - name: DB_USER
              value: app_de_con_owner_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-de-con-owner-user.app-de-con-db.credentials.postgresql.acid.zalan.do
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: app-de-con-backend
spec:
  selector:
    app: app-de-con-backend
  ports:
    - port: 8080
      targetPort: 80
