apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: app-de-con-db
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 3
  preparedDatabases:
    app_de_con:
      defaultUsers: true
  postgresql:
    version: "16"
